name: "publish-pages"
on:
    pull_request:
      types:
        - closed
jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: npm install react-scripts
        - run: npm install
        - run: npm run deploy
