name: "publish-pages"
on:
    pull_request:
      branches:
        - main
      types:
        - closed
jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - run: git config --global credential.helper store
        - run: git config --global user.email ${{ secrets.GIT_EMAIL }}
        - run: git config --global user.name ${{ secrets.GIT_USERNAME }}
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false
        - name: Reconfigure to use HTTPS authentication
          uses: GuillaumeFalourd/SSH-to-HTTPS@v1
          with:
            github_token: ${{secrets.GIT_PAT}}
        - run: npm install react-scripts
        - run: npm install
        - run: npm run deploy
