name: "publish-pages"
on:
    pull_request:
      branches:
        - main
      types:
        - closed
jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - uses: de-vri-es/setup-git-credentials@v2
          with:
            credentials: ${{secrets.GIT_CREDENTIAL}}
        - run: git config --global user.email ${{ secrets.GIT_EMAIL }}
        - run: git config --global user.name ${{ secrets.GIT_USERNAME }}
        - uses: actions/checkout@v2
        - run: npm install react-scripts
        - run: npm install
        - run: npm run deploy
