name: "publish-pages"
on:
    pull_request:
      branches:
        - main
      types:
        - closed
jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - run: git config --global user.email ${{ secrets.GIT_EMAIL }}
        - run: git config --global user.name ${{ secrets.GIT_USERNAME }}
        - uses: actions/checkout@v2
        - uses: oleksiyrudenko/gha-git-credentials@v2-latest
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'
        - uses: actions/setup-node@v1
          with:
            node-version: 16
        - run: npm ci
        - run: npm run deploy
